In [13]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [14]:
# outcome of one coin flip
np.random.randint(2, size=10000)

array([0, 0, 0, ..., 0, 1, 0])

In [15]:
# mean outcome of ten thousand coin flips
np.random.randint(2, size=10000).mean()

0.5013

In [16]:
# outcome of one coin flip
np.random.choice([0,1])

1

In [17]:
# outcome of ten thousand coin flips
np.random.choice([0,1], size=10000)

array([1, 0, 0, ..., 0, 0, 1])

In [18]:
# mean outcome of ten thousand coin flips
np.random.choice([0, 1], size=10000).mean()

0.4997

In [19]:
# outcomes of ten thousand biased coin flips
np.random.choice([0, 1], size=10000, p=[0.8, 0.2])

array([0, 0, 1, ..., 0, 1, 0])

In [20]:
# mean outcome of ten thousand biased coin flips
np.random.choice([0, 1], size=10000, p=[0.8, 0.2]).mean()

0.1921

In [21]:
int(1e6)

1000000

In [23]:
# simulate 1 million tests of two fair coin flips
tests = np.random.randint(2, size=(int(1e6), 2))
tests

array([[1, 0],
       [1, 1],
       [1, 1],
       ...,
       [0, 0],
       [0, 1],
       [1, 1]])

In [34]:
# sums of all tests
test_sums = tests.sum(axis=1)
test_sums

array([1, 2, 2, ..., 0, 1, 2])

In [36]:
# proportion of tests that produced exactly two heads
(test_sums == 0).mean()

0.249834

# PROBABILITY QUIZ

### 1. Two fair coin flips produce exactly two heads

In [37]:
# simulate 1 million tests of two fair coin flips
tests = np.random.randint(2, size=(int(1e6), 2))

# sums of all tests
test_sums = tests.sum(axis=1)

# proportion of tests that produced exactly two heads
(test_sums == 0).mean()

0.249954

### 2. Three fair coin flips produce exactly one head

In [60]:
tests = np.random.randint(2, size=(int(1e6), 3))

In [61]:
test_sums = tests.sum(axis=1)

In [62]:
(test_sums == 2).mean()

0.375318

### 3. Three biased coin flips with P(H) = 0.6 produce exactly one head

In [63]:
tests = np.random.choice([0,1], size=(int(1e6), 3), p=[0.6, 0.4])

# sums of all tests
test_sums = tests.sum(axis=1)

(test_sums == 2).mean()

0.288257

### 4. A die rolls an even number

In [77]:
tests = np.random.randint(1,high=7, size=int(1e6))

In [81]:
# proportion of tests that produced an even number
(tests%2 == 0).mean()

0.500524

### 5. Two dice roll a double

In [85]:
# simulate the first million die rolls
first = np.random.randint(1,high=7, size=int(1e6))

# simulate the second million die rolls
second = np.random.randint(1,high=7, size=int(1e6))

# proportion of tests where the 1st and 2nd die rolled the same number
(first == second).mean()

0.166354